### ISSUE TITLE
Entire <style> being removed by linkedom

### ISSUE THREAD

**Issue by Nashorn** [WebReflection/linkedom#40] opened 2021-02-25 15:44 UTC
After replacing jsdom with linkedom, i continued regression testing all the html src that i was previously pulling into this tool. Linkedom i noticed is removing entire blocks of <style> tags, no errors though, its just gone from the DOM after resave it to disk an open.

It's unfortunate, i had to reinstall jsdom, and all the hundreds of HTML src files are being processed again fine. I still have the linkedom commented for a future try again:

```
/*
var {parseHTML} = require('linkedom');
window.JSDOM = function JSDOM(html) { return parseHTML(html);} //facade to work like jsdom
*/

const jsdom = require("jsdom");
const { JSDOM } = jsdom;
window.JSDOM = JSDOM;
```

The benefits, design, efficiency and thought that went into linkedom is amazing, but it's a bit off to be a drop-in for jsdom. When dealing with HTML src that we have no control over, jsdom does swallow the errors (like octal syntax errors etc) and never mutates the DOM automatically.

Like the disappearing STYLE tag, no idea why linkedom just removes it, causing the page to be completely unformatted.

Will def come back to try this api out a few months from now, i'll keep a watch.

**Comment by Nashorn** [comment] 2021-02-25 15:49
A note to @WebReflection - 
I'd really like to see this api take off because of the algorithm you're using, way better on mem. Here's what i can suggest.

Save the .html source of atleast 10 sites. 
Load each into Linkedom, and then reexport to disk (take the **dom.window.document.documentElement.outerHTML**) without manipulating anything.

Then reopen each .html page to verify it's not mutated in any harsh ways. To make this api even more robust, it just MUST deal with the shitty, unimaginable crap HTML that devs could and would put out in the wild. It has to work, it has to be resilient.

**Comment by WebReflection** [comment] 2021-02-25 17:05
> but it's a bit off to be a drop-in for jsdom

you are comparing a month old software against the only industry standard to date to have DOM in JS ... yeah, sorry to disappoint.

**Comment by WebReflection** [comment] 2021-02-25 17:07
> Like the disappearing STYLE tag, no idea why linkedom just removes it, causing the page to be completely unformatted.

linkedom doesn't do that ... it could be a *htmlparser2* gotcha, or something to do with the way *style* elements are handled, because *style* elements are a weird *text only thing*.

the only way to help here, is to provide a file that fails ... otherwise there's nothing I can test against, hence I won't fix something I cannot reproduce or test.

**Comment by WebReflection** [comment] 2021-02-26 08:15
Version 0.5 now uses a different parsing mode for `htmlparser2` and all these issues *should* be gone.

closing regardless as there's no way to reproduce anything so, if you find another issue after updating to 0.5, feel free to open, but please provide a minimal reproducible example, thanks.

**Closed by WebReflection** 2021-02-26 08:15 UTC

**Comment by Nashorn** [comment] 2021-02-27 19:34
Are you on discord?

**Comment by WebReflection** [comment] 2021-02-28 08:24
no discord, but my projects discussions are here https://github.com/WebReflection/discussions/discussions
