### ISSUE TITLE
Clarification on relationship to DOM standards

### ISSUE THREAD

**Issue by brainkim** [WebReflection/linkedom#32] opened 2021-02-23 00:15 UTC
Thanks for working on and publishing this project. I’d like some clarification on this line of the project README, which states:

> - be close to the current DOM standard, but not too close.

What are this project’s design goals with regard to DOM standards? If LinkeDOM is not aligned with WHATWG standards, where does it diverge? Is there a general rule of thumb or list of differences describing what’s in scope for the project?

**Comment by WebReflection** [comment] 2021-02-23 10:01
> What are this project’s design goals with regard to DOM standards?

Be useful for the common case, ignore everything irrelevant, bloated, legacy, non-common, useless for real-world applications.

As example, nobody cares about live collections in the SSR world, and Custom Elements and MutationObserver are already a stretch of what's really necessary to work with the DOM on the Server, or in a Worker, or any other DOM-less environment.

> Is there a general rule of thumb or list of differences describing what’s in scope for the project?

Yes:

  * try it for your use case, it should just work.
  * if it doesn't, check out the element that doesn't behave as expected within the *html* folder, and see if the accessor you are after has been implemented.
  * if it didn't, check [how to contribute](https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md) session to file a *PR*
  * if it's broken, check [how to contribute](https://github.com/WebReflection/linkedom/blob/main/how-to-contribute.md) session to file a bug
  * if you are after a legacy quirk, something extremely rare, or something that could compromise performance all over, use another tool designed to test 1:1 behavior with the living standard, like *JSDOM*

I hope this answers your question. Happy to elaborate more, if needed, but I'll close this as it's not a bug 👋

**Closed by WebReflection** 2021-02-23 10:01 UTC
