### ISSUE TITLE
`getAttribute` for a SVG returning a `SVGAnimatedString`

### ISSUE THREAD

**Issue by SettingDust** [WebReflection/linkedom#121] opened 2022-03-25 01:54 UTC
`getAttribute` should return a string containing the value.
https://dom.spec.whatwg.org/#dom-element-getattribute
> Return attr’s [value](https://dom.spec.whatwg.org/#concept-attribute-value).

https://dom.spec.whatwg.org/#concept-attribute-value
> value (a string)

**Comment by WebReflection** [comment] 2022-03-25 12:42
@SettingDust is this a `class` thing only? the `className` is [very weird in SVG](https://github.com/WebReflection/linkedom/issues/120#issuecomment-1064089939) but I wonder if, beside fixing `class`, there are issues with other attributes

**Comment by SettingDust** [comment] 2022-03-25 15:54
https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement
https://svgwg.org/svg2-draft/types.html#InterfaceSVGURIReference


Thats all I founded

**Comment by WebReflection** [comment] 2022-03-25 17:02
> SVG Element className should be a SVGAnimatedString object.

that's more or less reflected here, but also zero interest in making it full specs compliant ... so the bug is around `svgElement.getAttribute('class')` and nothing else, right?

**Comment by daveschumaker** [comment] 2022-03-25 18:31
Hello 👋 

Forgive me for lurking, but I might have some helpful additional context.

I've pulled this project down to my machine and have been attempting to fix this issue. This might be related to my limited understanding of the SVG spec, but I'm not entirely sure the issue is with the class attribute. I've been running some tests related to an SVG where I first noticed this issue occurring. 

`test/svg/element.js` fails when encountering this:

```
// const svgString = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" role="img" aria-labelledby="ainxk40s6wcy2elfekejc3szjrwhw6pw" class="crayons-icon"><title id="ainxk40s6wcy2elfekejc3szjrwhw6pw">Search</title><path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0111 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 01-1.969 5.617zm-2.006-.742A6.977 6.977 0 0018 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 004.875-1.975l.15-.15z"></path></svg>`

// Original test that passes.
// document = (new DOMParser).parseFromString(`<!doctype html><html><svg><rect /></svg></html>`, 'text/html');

document = (new DOMParser).parseFromString(`<!doctype html><html>${svgString}</html>`, 'text/html');

```

The test fails with the following error in my terminal:
```
(node:97574) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'ownerSVGElement' in null
    at Object.<anonymous> (/Users/dave/projects/github/linkedom/test/svg/element.js:39:26)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /Users/dave/projects/github/linkedom/test/index.js:19:7
```

Alright, let's strip out all attributes in the `svg` tag and see what happenes.
```
const svgString = `<svg><title id="ainxk40s6wcy2elfekejc3szjrwhw6pw">Search</title><path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0111 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 01-1.969 5.617zm-2.006-.742A6.977 6.977 0 0018 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 004.875-1.975l.15-.15z"></path></svg>`
```

Same error. Interesting. Let's strip out the `title` tag inside the SVG.

```
const svgString = `<svg><path d="M18.031 16.617l4.283 4.282-1.415 1.415-4.282-4.283A8.96 8.96 0 0111 20c-4.968 0-9-4.032-9-9s4.032-9 9-9 9 4.032 9 9a8.96 8.96 0 01-1.969 5.617zm-2.006-.742A6.977 6.977 0 0018 11c0-3.868-3.133-7-7-7-3.868 0-7 3.132-7 7 0 3.867 3.132 7 7 7a6.977 6.977 0 004.875-1.975l.15-.15z"></path></svg>`
```

Still fails. Same error!

Maybe there is something funky with the path. Let's paste in a simple example from the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes).

```
const svgString = `<svg width="200" height="250" version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M20,230 Q40,205 50,230 T90,230" fill="none" stroke="blue" stroke-width="5"/></svg>`
```

Same error.

Okay, this is interesting. Maybe it isn't the attributes in the SVG tag, but something to do with child elements instead? Here is a test with all the original attributes in my first test, but replacing `<path ... />` with `<rect />`;

```
const svgString = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" role="img" aria-labelledby="ainxk40s6wcy2elfekejc3szjrwhw6pw" class="crayons-icon"><rect /></svg>`

```

Hot diggity. The test passes!

So, it appears to me to be an issue with what types of elements are present within the `SVG` tag.

**Comment by WebReflection** [comment] 2022-03-25 19:28
@daveschumaker there is a 100% code coverage here, so it shouldn't be too difficult to the test that passes, and point at what variant of that test would fail.

As gently reminder, this project cares zero about JSDOM covered use cases, it's more about SSR, not testing, but there's no way I can write this over and over and have people understanding it, so I'm OK improving compatibility here and there, but by no mean this project goal is to be 100% specs compliant.

If we're all on the same page here, good! Let's try to understand what is it that is not working with `getAttribute`, and file different bugs with different test / use cases when it has nothing to do with attributes, shall we?

thank you!

**Comment by WebReflection** [comment] 2022-03-25 19:31
because [explicit](https://github.com/WebReflection/linkedom#faq) is better than implicit:

![Screenshot from 2022-03-25 20-30-38](https://user-images.githubusercontent.com/85749/160188931-243939d0-c9b7-49fb-a2ff-a80a9fa33ad1.png)

**Comment by SettingDust** [comment] 2022-03-26 02:22
> > SVG Element className should be a SVGAnimatedString object.
> 
> that's more or less reflected here, but also zero interest in making it full specs compliant ... so the bug is around `svgElement.getAttribute('class')` and nothing else, right?

right

**Comment by WebReflection** [comment] 2022-03-26 23:00
@SettingDust this should be fixed, thanks 👋

**Closed** 2022-03-26 23:00 UTC
